insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (1, false, 0.29, 1.34, 'Agivu', 'Programmable zero administration support');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (2, false, 0.1, 1.88, 'Oloo', 'Visionary neutral utilisation');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (3, true, 0.23, 1.21, 'Jabbersphere', 'Polarised web-enabled orchestration');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (4, true, 0.26, 1.16, 'Yakitri', 'Down-sized fault-tolerant solution');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (5, false, 0.24, 1.48, 'Edgepulse', 'Stand-alone contextually-based service-desk');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (6, false, 0.26, 1.34, 'Browsecat', 'Pre-emptive impactful hierarchy');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (7, true, 0.29, 1.69, 'Leenti', 'Switchable cohesive intranet');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (8, true, 0.24, 1.03, 'Tambee', 'Open-architected zero defect definition');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (9, true, 0.27, 1.68, 'Ainyx', 'Profound bifurcated framework');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (10, false, 0.13, 1.83, 'Gabvine', 'Focused 24 hour functionalities');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (11, false, 0.14, 1.15, 'Yadel', 'Networked stable definition');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (12, false, 0.22, 1.2, 'Abatz', 'Progressive multi-state contingency');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (13, true, 0.19, 1.72, 'Dabtype', 'Quality-focused interactive database');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (14, false, 0.21, 1.15, 'Ntag', 'Intuitive asynchronous open architecture');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (15, false, 0.14, 1.45, 'Browsezoom', 'De-engineered bi-directional alliance');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (16, true, 0.29, 1.75, 'Bubblebox', 'Self-enabling real-time analyzer');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (17, true, 0.15, 1.73, 'Realbuzz', 'Organized local workforce');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (18, false, 0.13, 1.67, 'Teklist', 'Reactive national matrices');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (19, false, 0.29, 1.7, 'Gabvine', 'Synchronised multimedia access');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (20, false, 0.27, 1.48, 'Meetz', 'Business-focused incremental instruction set');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (21, false, 0.15, 1.75, 'Skimia', 'Networked scalable open system');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (22, false, 0.15, 1.82, 'Aimbo', 'Implemented value-added model');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (23, true, 0.26, 1.61, 'Quaxo', 'Vision-oriented methodical methodology');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (24, true, 0.13, 1.99, 'Voonte', 'Virtual scalable budgetary management');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (25, false, 0.23, 1.97, 'Tagcat', 'Team-oriented zero tolerance architecture');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (26, true, 0.17, 1.63, 'Quatz', 'Customizable upward-trending methodology');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (27, false, 0.27, 1.92, 'Eamia', 'Polarised scalable knowledge base');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (28, false, 0.11, 1.22, 'Tagfeed', 'Monitored exuding website');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (29, true, 0.18, 1.77, 'Realfire', 'Exclusive full-range challenge');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (30, true, 0.18, 1.3, 'Izio', 'Reactive coherent benchmark');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (31, false, 0.2, 1.71, 'Linkbuzz', 'Diverse dynamic solution');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (32, false, 0.22, 1.72, 'Zooxo', 'Virtual actuating capability');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (33, true, 0.28, 1.46, 'Plajo', 'Stand-alone optimal paradigm');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (34, true, 0.21, 1.3, 'Livetube', 'Synchronised 6th generation local area network');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (35, false, 0.14, 1.05, 'Bubblebox', 'Pre-emptive systematic Graphical User Interface');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (36, false, 0.12, 1.65, 'Topicstorm', 'Organized composite task-force');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (37, true, 0.2, 1.86, 'Mita', 'Robust object-oriented capacity');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (38, true, 0.12, 1.82, 'Skynoodle', 'User-centric heuristic interface');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (39, true, 0.14, 1.03, 'Tagpad', 'Front-line client-driven website');
insert into Publicite (publicite_id, sponsored, CPV, CPC, brand, name) values (40, false, 0.21, 1.89, 'Avamm', 'Universal empowering architecture');
